window.COURSE_MODULES = [
  {
    id: "alphabet",
    title: "Alphabet and Pronunciation",
    goal: "Learn the 29 Swedish letters, hear Å, Ä, Ö clearly, and notice long and short vowels before you memorize phrases.",
    sourceNote: "Starter pronunciation points follow common beginner guidance: Swedish has A-Z plus Å, Ä, Ö, and vowel length changes meaning.",
    notes: [
      "Swedish has 29 letters: A-Z plus Å, Ä, Ö. Å, Ä, Ö are separate letters at the end of the alphabet.",
      "Vowels are central in Swedish. Practice long and short pairs slowly: tak / tack, mat / matt.",
      "A short stressed vowel is often followed by two consonants. That is why tack has a shorter vowel than tak.",
      "G and K can sound different before soft vowels. Start by noticing ge, gick, kök, kaffe.",
      "Daily routine: play the alphabet once, then drill Å, Ä, Ö in real words."
    ],
    practice: [
      ["Alphabet pass", "Listen to the full alphabet, then repeat A-F, G-L, M-S, T-Z, Å-Ö."],
      ["Special letters", "Say å, ä, ö, then say språk, träffas, förstår."],
      ["Length check", "Say tak and tack. Hold the vowel longer in tak and shorter in tack."],
      ["Spelling habit", "Spell your name aloud using Swedish letter names."]
    ],
    vocabulary: [
      ["å", "Swedish letter Å", "Sounds roughly like the vowel in English 'more'."],
      ["ä", "Swedish letter Ä", "Often close to 'air' or 'e' depending on word."],
      ["ö", "Swedish letter Ö", "Rounded vowel, not the same as English O."],
      ["språk", "language"],
      ["träffas", "meet / see each other"],
      ["förstår", "understand"],
      ["tak", "roof"],
      ["tack", "thanks"],
      ["mat", "food"],
      ["matt", "tired / dull"],
      ["kök", "kitchen"],
      ["kaffe", "coffee"]
    ],
    examples: ["å", "ä", "ö", "språk", "träffas", "förstår", "tak", "tack", "mat", "matt", "kök", "kaffe"]
  },
  {
    id: "intro",
    title: "Names, Languages, and Countries",
    goal: "Introduce yourself, ask basic personal questions, and build a short first conversation.",
    sourceNote: "This module focuses on high-frequency A1 introduction phrases used in beginner Swedish courses.",
    notes: [
      "Jag heter ... means I am called ... and is the normal way to give your name.",
      "Varifrån kommer du? asks where someone is from. Answer with Jag kommer från ...",
      "Vad talar du för språk? asks which languages someone speaks.",
      "Jag talar engelska och lite svenska means I speak English and a little Swedish.",
      "Keep your first answers short, correct, and speakable before you make them longer."
    ],
    practice: [
      ["Question chain", "Vad heter du? Varifrån kommer du? Vad talar du för språk?"],
      ["Rony answer", "Jag heter Rony. Jag kommer från Indien. Jag talar engelska och lite svenska."],
      ["Polite close", "Trevligt att träffas. Vi ses!"],
      ["Swap details", "Change the name, country, city, and languages, then play your new introduction if audio exists."]
    ],
    vocabulary: [
      ["hej", "hello / hi"],
      ["vad", "what"],
      ["heter", "am/is/are called"],
      ["du", "you"],
      ["jag", "I"],
      ["kommer från", "come from"],
      ["Indien", "India"],
      ["talar", "speak"],
      ["språk", "language"],
      ["engelska", "English"],
      ["lite", "a little"],
      ["svenska", "Swedish"],
      ["trevligt att träffas", "nice to meet you"],
      ["vi ses", "see you"]
    ],
    examples: ["Hej!", "Vad heter du?", "Jag heter Rony.", "Varifrån kommer du?", "Jag kommer från Indien.", "Vad talar du för språk?", "Jag talar engelska och lite svenska.", "Trevligt att träffas.", "Vi ses!"]
  },
  {
    id: "wordorder",
    title: "Word Order and Questions",
    goal: "Recognize Swedish verb position in statements, yes/no questions, and question-word questions.",
    sourceNote: "Beginner Swedish commonly teaches verb-second word order in main clauses and verb-first order in yes/no questions.",
    notes: [
      "Basic statement: subject + verb + rest. Jag bor i Stockholm.",
      "Yes/no question: verb + subject + rest. Bor du i Stockholm?",
      "Question-word pattern: question word + verb + subject. Vad heter du?",
      "The verb often sits in position 2 in main clauses: I dag studerar jag svenska.",
      "Do not translate English word order too directly. Train the pattern aloud."
    ],
    practice: [
      ["Statement", "Du talar svenska."],
      ["Make a yes/no question", "Talar du svenska?"],
      ["Question word", "Vad talar du för språk?"],
      ["Move time first", "I dag studerar jag svenska."]
    ],
    vocabulary: [
      ["ordföljd", "word order"],
      ["fråga", "question"],
      ["påstående", "statement"],
      ["verb", "verb"],
      ["subjekt", "subject"],
      ["du", "you"],
      ["talar", "speak"],
      ["svenska", "Swedish"],
      ["vad", "what"],
      ["för", "for / what kind of", "Used in 'Vad talar du för språk?'"],
      ["i dag", "today"],
      ["studerar", "study"]
    ],
    examples: ["Jag bor i Stockholm.", "Bor du i Stockholm?", "Du talar svenska.", "Talar du svenska?", "Vad heter du?", "Vad talar du för språk?", "I dag studerar jag svenska."]
  },
  {
    id: "verbs",
    title: "Pronouns and Present Tense",
    goal: "Use core pronouns with common present-tense verbs for everyday A1 sentences.",
    sourceNote: "The practice emphasizes stable present-tense forms and whole useful phrases before abstract conjugation.",
    notes: [
      "Core pronouns: jag, du, han, hon, vi, ni, de.",
      "Many present-tense verbs end in -r: talar, heter, kommer, förstår, bor, studerar.",
      "The present form is the same with different subjects: jag talar, du talar, vi talar.",
      "Negation goes after the verb in a simple main clause: Jag förstår inte.",
      "Memorize short sentence chunks first, then swap the subject or verb."
    ],
    practice: [
      ["Pronoun drill", "jag, du, han, hon, vi, ni, de"],
      ["Verb drill", "heter, kommer, talar, förstår, bor, studerar"],
      ["Positive", "Jag studerar svenska."],
      ["Negative", "Jag förstår inte."]
    ],
    vocabulary: [
      ["jag", "I"],
      ["du", "you"],
      ["han", "he"],
      ["hon", "she"],
      ["vi", "we"],
      ["ni", "you plural / polite you"],
      ["de", "they"],
      ["heter", "am/is/are called"],
      ["kommer", "come / comes"],
      ["talar", "speak / speaks"],
      ["förstår", "understand / understands"],
      ["bor", "live / lives"],
      ["studerar", "study / studies"],
      ["inte", "not"],
      ["lite", "a little"],
      ["från", "from"],
      ["Sverige", "Sweden"]
    ],
    examples: ["jag", "du", "vi", "Jag bor i Stockholm.", "Jag studerar svenska.", "Jag förstår lite.", "Jag förstår inte.", "Vi talar engelska.", "Hon kommer från Sverige."]
  },
  {
    id: "verbTenses",
    title: "Infinitive Verbs and Tenses",
    goal: "Practice common infinitive verbs in present, past, perfect, and future with short useful sentences.",
    sourceNote: "This module extends the verb table with quiz practice for infinitive forms and core tense patterns.",
    notes: [
      "The infinitive often starts with att: att prata, att äta, att läsa.",
      "Present tense tells what happens now or usually: Jag pratar nu.",
      "Past tense tells what happened before: Jag pratade i går.",
      "Perfect tense uses har + supine: Jag har pratat i dag.",
      "Future often uses ska + infinitive or kommer att + infinitive."
    ],
    practice: [
      ["Infinitive", "att prata, att äta, att läsa, att skriva"],
      ["Present", "Jag pratar nu. Jag äter frukost. Jag läser boken."],
      ["Past", "Jag pratade i går. Jag åt lunch. Jag läste brevet."],
      ["Perfect", "Jag har pratat i dag. Jag har ätit middag. Jag har läst sidan."],
      ["Future", "Jag ska prata snart. Jag ska äta snart. Jag kommer att behöva tid."]
    ],
    vocabulary: [
      ["att prata", "to talk"],
      ["att äta", "to eat"],
      ["att läsa", "to read"],
      ["att skriva", "to write"],
      ["att gå", "to go / walk"],
      ["att göra", "to do / make"],
      ["att behöva", "to need"],
      ["att förstå", "to understand"],
      ["nutid", "present tense"],
      ["dåtid", "past tense"],
      ["perfekt", "perfect tense"],
      ["framtid", "future tense"]
    ],
    examples: ["att prata", "Jag pratar nu.", "Jag pratade i går.", "Jag har pratat i dag.", "Jag ska prata snart.", "Jag kommer att behöva tid."]
  },
  {
    id: "numbers",
    title: "Numbers and Time",
    goal: "Count to 100, understand the pattern up to 1000, ask for the time, and say a phone number clearly.",
    sourceNote: "Numbers and time are included because they create immediate listening practice and daily-life usefulness.",
    notes: [
      "Learn 0-10 first: noll, en, två, tre, fyra, fem, sex, sju, åtta, nio, tio.",
      "Then add 11-20: elva, tolv, tretton, fjorton, femton, sexton, sjutton, arton, nitton, tjugo.",
      "After 20, Swedish combines tens and ones: tjugoen, tjugotvå, trettiofem, fyrtioåtta.",
      "The tens are: tjugo, trettio, fyrtio, femtio, sextio, sjuttio, åttio, nittio, hundra.",
      "Hundreds use the same pattern: etthundra, tvåhundra, trehundra. 245 is tvåhundrafyrtiofem.",
      "Vad är klockan? means What time is it?",
      "Klockan är ett means It is one o'clock. Klockan är två means It is two o'clock.",
      "For phone numbers, say the digits in small groups: noll sju noll, ett två tre, fyrtiofem, sextiosju."
    ],
    practice: [
      ["0-10", "noll, en, två, tre, fyra, fem, sex, sju, åtta, nio, tio"],
      ["11-20", "elva, tolv, tretton, fjorton, femton, sexton, sjutton, arton, nitton, tjugo"],
      ["20-100", "tjugo, trettio, fyrtio, femtio, sextio, sjuttio, åttio, nittio, hundra"],
      ["Examples to 100", "tjugoen, trettiofem, fyrtioåtta, femtiotvå, sextiosex, sjuttiosju, åttiofyra, nittionio"],
      ["Examples to 1000", "etthundra, tvåhundra, tvåhundrafyrtiofem, femhundrasextio, niohundranittionio, ett tusen"],
      ["Phone number", "Mitt telefonnummer är noll sju noll, ett två tre, fyrtiofem, sextiosju."],
      ["Ask time", "Vad är klockan?"],
      ["Answer time", "Klockan är ett. Klockan är två."]
    ],
    vocabulary: [
      ["noll", "zero"],
      ["en / ett", "one"],
      ["två", "two"],
      ["tre", "three"],
      ["fyra", "four"],
      ["fem", "five"],
      ["sex", "six"],
      ["sju", "seven"],
      ["åtta", "eight"],
      ["nio", "nine"],
      ["tio", "ten"],
      ["elva", "eleven"],
      ["tolv", "twelve"],
      ["tretton", "thirteen"],
      ["fjorton", "fourteen"],
      ["femton", "fifteen"],
      ["sexton", "sixteen"],
      ["sjutton", "seventeen"],
      ["arton", "eighteen"],
      ["nitton", "nineteen"],
      ["tjugo", "twenty"],
      ["trettio", "thirty"],
      ["fyrtio", "forty"],
      ["femtio", "fifty"],
      ["sextio", "sixty"],
      ["sjuttio", "seventy"],
      ["åttio", "eighty"],
      ["nittio", "ninety"],
      ["hundra", "one hundred / hundred"],
      ["tusen", "one thousand / thousand"],
      ["tjugoen", "twenty-one"],
      ["trettiofem", "thirty-five"],
      ["tvåhundrafyrtiofem", "two hundred forty-five"],
      ["telefonnummer", "phone number"],
      ["Mitt telefonnummer är ...", "My phone number is ..."],
      ["klockan", "the clock / the time"],
      ["Vad är klockan?", "What time is it?"]
    ],
    examples: ["noll", "en", "två", "tre", "fyra", "fem", "sex", "sju", "åtta", "nio", "tio", "elva", "tolv", "tjugo", "Vad är klockan?", "Klockan är ett.", "Klockan är två."]
  },
  {
    id: "food",
    title: "Cafe and Shopping Basics",
    goal: "Order something simple, ask the price, and use polite service phrases.",
    sourceNote: "The phrases are starter A1 survival language for cafes, shops, and polite exchanges.",
    notes: [
      "Jag skulle vilja ha ... is a polite way to say I would like ...",
      "Vad kostar det? asks How much does it cost?",
      "Tack means thank you. Varsågod can mean please, here you go, or you're welcome.",
      "Use en/ett with nouns when possible: en kaffe, ett vatten, ett bröd.",
      "Practice tiny dialogues so the words connect to real situations."
    ],
    practice: [
      ["Order", "Jag skulle vilja ha kaffe, tack."],
      ["Ask price", "Vad kostar det?"],
      ["Pay and thank", "Tack. Varsågod."],
      ["Swap item", "Jag skulle vilja ha vatten. Jag skulle vilja ha bröd."]
    ],
    vocabulary: [
      ["jag skulle vilja ha", "I would like"],
      ["kaffe", "coffee"],
      ["vatten", "water"],
      ["bröd", "bread"],
      ["mjölk", "milk"],
      ["tack", "thank you / thanks"],
      ["varsågod", "please / here you go / you're welcome"],
      ["vad", "what"],
      ["kostar", "costs"],
      ["det", "it / that"],
      ["en kaffe", "a coffee"],
      ["ett vatten", "a water"]
    ],
    examples: ["Jag skulle vilja ha kaffe.", "Jag skulle vilja ha vatten.", "Vad kostar det?", "Tack.", "Varsågod.", "vatten", "bröd", "mjölk", "kaffe", "en kaffe", "ett vatten"]
  },
  {
    id: "workbook",
    title: "Workbook Practice",
    goal: "Turn textbook and workbook exercises into repeatable speaking, writing, and review habits.",
    sourceNote: "This module is a study-process module: write first, check, speak aloud, then review missed items.",
    notes: [
      "Do not only read the answer key. Write first, check second, speak third.",
      "When you miss an answer, repeat it the next day.",
      "Learn nouns with en or ett and say the full noun phrase aloud.",
      "Use the textbook model before doing workbook exercises.",
      "Short daily practice beats one long session."
    ],
    practice: [
      ["Before workbook", "Read the matching textbook model once aloud."],
      ["During workbook", "Write the answer without looking at the key."],
      ["After checking", "Say the corrected sentence aloud three times."],
      ["Next day", "Review only missed answers first."]
    ],
    vocabulary: [
      ["en", "a/an", "Common-gender article."],
      ["ett", "a/an", "Neuter article."],
      ["bok", "book"],
      ["språk", "language"],
      ["boken", "the book"],
      ["språket", "the language"],
      ["övar", "practice / practices"],
      ["svenska", "Swedish"],
      ["varje dag", "every day"],
      ["skriver", "write / writes"],
      ["svaret", "the answer"],
      ["läser högt", "read aloud / reads aloud"]
    ],
    examples: ["en bok", "ett språk", "boken", "språket", "Jag övar svenska varje dag.", "Jag skriver svaret.", "Jag läser högt."]
  }
];

window.COURSE_QUIZ = [
  { module: "alphabet", q: "How many letters are in the Swedish alphabet?", options: ["29", "26", "30"], answer: "29" },
  { module: "alphabet", q: "Which letters come at the end of the Swedish alphabet?", options: ["Å, Ä, Ö", "Ä, Ö, Å", "Ö, Å, Ä"], answer: "Å, Ä, Ö" },
  { module: "alphabet", q: "How do you say the letter W in Swedish?", options: ["dubbel-ve", "ve", "ess"], answer: "dubbel-ve" },
  { module: "alphabet", q: "Which word has Å?", options: ["språk", "svenska", "tack"], answer: "språk" },
  { module: "alphabet", q: "Which word has Ä?", options: ["träffas", "kommer", "bok"], answer: "träffas" },
  { module: "alphabet", q: "Which word has Ö?", options: ["förstår", "kaffe", "penna"], answer: "förstår" },
  { module: "alphabet", q: "Which pair is best for long vs short vowel practice?", options: ["tak / tack", "hej / jag", "bok / språk"], answer: "tak / tack" },
  { module: "alphabet", q: "What usually happens before two consonants in a stressed syllable?", options: ["The vowel is shorter", "The vowel disappears", "The word becomes English"], answer: "The vowel is shorter" },
  { module: "alphabet", q: "Which word should you use to practice Ö?", options: ["kök", "mat", "hej"], answer: "kök" },
  { module: "alphabet", q: "Which is a good daily pronunciation routine?", options: ["Alphabet, then Å Ä Ö words", "Only silent reading", "Skip letters after Z"], answer: "Alphabet, then Å Ä Ö words" },

  { module: "intro", q: "Translate: My name is Rony.", options: ["Jag heter Rony.", "Jag kommer Rony.", "Jag bor Rony."], answer: "Jag heter Rony." },
  { module: "intro", q: "Translate: I come from India.", options: ["Jag kommer från Indien.", "Jag talar Indien.", "Jag heter Indien."], answer: "Jag kommer från Indien." },
  { module: "intro", q: "Translate: What languages do you speak?", options: ["Vad talar du för språk?", "Var bor du?", "Vad heter du?"], answer: "Vad talar du för språk?" },
  { module: "intro", q: "What does 'Varifrån kommer du?' mean?", options: ["Where are you from?", "Where do you live?", "What is your name?"], answer: "Where are you from?", audio: "Varifrån kommer du?" },
  { module: "intro", q: "Which sentence says I speak English and a little Swedish?", options: ["Jag talar engelska och lite svenska.", "Jag kommer från engelska.", "Jag heter svenska."], answer: "Jag talar engelska och lite svenska." },
  { module: "intro", q: "Choose the reply to 'Trevligt att träffas.'", options: ["Trevligt att träffas.", "Jag bor.", "Vad kostar det?"], answer: "Trevligt att träffas." },
  { module: "intro", q: "Which question asks someone's name?", options: ["Vad heter du?", "Vad kostar det?", "Vad är klockan?"], answer: "Vad heter du?" },
  { module: "intro", q: "Which is a short self-introduction?", options: ["Hej! Jag heter Rony.", "Tack kostar klockan.", "Sju kaffe bor."], answer: "Hej! Jag heter Rony." },
  { module: "intro", q: "Which word means languages?", options: ["språk", "klockan", "vatten"], answer: "språk" },
  { module: "intro", q: "Which phrase means see you?", options: ["Vi ses!", "Varsågod!", "Vad kostar det?"], answer: "Vi ses!" },

  { module: "wordorder", q: "Choose the correct statement.", options: ["Jag bor i Stockholm.", "Bor jag i Stockholm?", "I Stockholm jag bor."], answer: "Jag bor i Stockholm." },
  { module: "wordorder", q: "Choose the correct yes/no question.", options: ["Bor du i Stockholm?", "Du bor i Stockholm?", "I Stockholm bor du."], answer: "Bor du i Stockholm?" },
  { module: "wordorder", q: "What comes second in many Swedish main clauses?", options: ["The verb", "The adjective", "The country"], answer: "The verb" },
  { module: "wordorder", q: "Choose the question-word pattern.", options: ["Vad heter du?", "Du heter vad?", "Heter vad du?"], answer: "Vad heter du?" },
  { module: "wordorder", q: "Choose the yes/no question.", options: ["Du talar svenska.", "Talar du svenska?", "Vad talar du?"], answer: "Talar du svenska?" },
  { module: "wordorder", q: "Turn 'Du studerar svenska' into a question.", options: ["Studerar du svenska?", "Du studerar svenska?", "Vad studerar du svenska?"], answer: "Studerar du svenska?" },
  { module: "wordorder", q: "Which sentence has time first with verb second?", options: ["I dag studerar jag svenska.", "I dag jag studerar svenska.", "Studerar i dag jag svenska."], answer: "I dag studerar jag svenska." },
  { module: "wordorder", q: "Which is the subject in 'Bor du i Stockholm?'", options: ["du", "bor", "Stockholm"], answer: "du" },
  { module: "wordorder", q: "Which starts with a question word?", options: ["Vad talar du?", "Talar du svenska?", "Du talar svenska."], answer: "Vad talar du?" },
  { module: "wordorder", q: "What is the safest beginner pattern for a statement?", options: ["Subject + verb + rest", "Verb + verb + subject", "English order every time"], answer: "Subject + verb + rest" },

  { module: "verbs", q: "Which means 'I'?", options: ["jag", "du", "vi"], answer: "jag" },
  { module: "verbs", q: "Which means 'we'?", options: ["vi", "ni", "de"], answer: "vi" },
  { module: "verbs", q: "Which means 'you' singular?", options: ["du", "jag", "hon"], answer: "du" },
  { module: "verbs", q: "Translate: I live in Stockholm.", options: ["Jag bor i Stockholm.", "Jag är i Stockholm.", "Jag har Stockholm."], answer: "Jag bor i Stockholm." },
  { module: "verbs", q: "Translate: I study Swedish.", options: ["Jag studerar svenska.", "Jag talar svenska.", "Jag kommer svenska."], answer: "Jag studerar svenska." },
  { module: "verbs", q: "Which present tense verb means understand?", options: ["förstår", "kommer", "heter"], answer: "förstår" },
  { module: "verbs", q: "Which phrase is correct?", options: ["Vi talar engelska.", "Vi talar engelskaer.", "Vi tala engelska."], answer: "Vi talar engelska." },
  { module: "verbs", q: "Where does 'inte' go in 'Jag förstår inte'?", options: ["After the verb", "Before jag", "After nothing"], answer: "After the verb" },
  { module: "verbs", q: "Which is a present-tense verb?", options: ["studerar", "svenska", "Stockholm"], answer: "studerar" },
  { module: "verbs", q: "Which sentence means I do not understand?", options: ["Jag förstår inte.", "Jag heter inte.", "Jag kommer inte svenska."], answer: "Jag förstår inte." },

  { module: "verbTenses", q: "Choose the infinitive for 'to talk'.", options: ["att prata", "pratar", "pratade"], answer: "att prata" },
  { module: "verbTenses", q: "Choose the present tense: I am talking now.", options: ["Jag pratar nu.", "Jag pratade i går.", "Jag har pratat i dag."], answer: "Jag pratar nu." },
  { module: "verbTenses", q: "Choose the past tense: I ate lunch.", options: ["Jag åt lunch.", "Jag äter frukost.", "Jag ska äta snart."], answer: "Jag åt lunch." },
  { module: "verbTenses", q: "Choose the perfect tense: I have read the page.", options: ["Jag har läst sidan.", "Jag läste brevet.", "Jag läser boken."], answer: "Jag har läst sidan." },
  { module: "verbTenses", q: "Choose the future tense: I will write now.", options: ["Jag ska skriva nu.", "Jag skrev ett mejl.", "Jag skriver svaret."], answer: "Jag ska skriva nu." },
  { module: "verbTenses", q: "Which sentence means I lived in India?", options: ["Jag bodde i Indien.", "Jag bor i Stockholm.", "Jag har bott här."], answer: "Jag bodde i Indien." },
  { module: "verbTenses", q: "Which sentence is perfect tense?", options: ["Jag har jobbat mycket.", "Jag jobbar i dag.", "Jag jobbade i går."], answer: "Jag har jobbat mycket." },
  { module: "verbTenses", q: "Which sentence uses future with kommer att?", options: ["Jag kommer att behöva tid.", "Jag behövde vila.", "Jag behöver vatten."], answer: "Jag kommer att behöva tid." },
  { module: "verbTenses", q: "Choose the past tense of att gå.", options: ["Jag gick till skolan.", "Jag går hem.", "Jag har gått långt."], answer: "Jag gick till skolan." },
  { module: "verbTenses", q: "Choose the perfect tense of att göra.", options: ["Jag har gjort klart.", "Jag gör kaffe.", "Jag gjorde läxan."], answer: "Jag har gjort klart." },
  { module: "verbTenses", q: "Which sentence means I will meet a friend?", options: ["Jag ska träffa en vän.", "Jag träffade läraren.", "Jag träffar Anna."], answer: "Jag ska träffa en vän." },
  { module: "verbTenses", q: "Choose the sentence in present tense.", options: ["Jag förstår frågan.", "Jag förstod texten.", "Jag har förstått regeln."], answer: "Jag förstår frågan." },
  { module: "verbTenses", q: "Which sentence means I have learned a lot?", options: ["Jag har lärt mig mycket.", "Jag lär mig svenska.", "Jag lärde mig ordet."], answer: "Jag har lärt mig mycket." },
  { module: "verbTenses", q: "Choose the future tense of att öva.", options: ["Jag ska öva varje dag.", "Jag övade verb.", "Jag har övat mycket."], answer: "Jag ska öva varje dag." },
  { module: "verbTenses", q: "Which Swedish sentence means I forgot the book?", options: ["Jag glömde boken.", "Jag glömmer namnet.", "Jag har glömt nyckeln."], answer: "Jag glömde boken." },

  { module: "numbers", q: "What is 2 in Swedish?", options: ["två", "tre", "tio"], answer: "två" },
  { module: "numbers", q: "What is 7 in Swedish?", options: ["sju", "sex", "åtta"], answer: "sju" },
  { module: "numbers", q: "What is 10 in Swedish?", options: ["tio", "tolv", "tre"], answer: "tio" },
  { module: "numbers", q: "What is 12 in Swedish?", options: ["tolv", "tjugo", "två"], answer: "tolv" },
  { module: "numbers", q: "Translate: It is one o'clock.", options: ["Klockan är ett.", "Klockan är tio.", "Vad är klockan?"], answer: "Klockan är ett." },
  { module: "numbers", q: "What does 'Vad är klockan?' mean?", options: ["What time is it?", "What does it cost?", "Where do you live?"], answer: "What time is it?", audio: "Vad är klockan?" },
  { module: "numbers", q: "Which sequence is 0-5?", options: ["noll, en, två, tre, fyra, fem", "en, två, sju, tio", "sex, sju, åtta, nio"], answer: "noll, en, två, tre, fyra, fem" },
  { module: "numbers", q: "Which number is åtta?", options: ["8", "7", "18"], answer: "8" },
  { module: "numbers", q: "Which phrase says it is two o'clock?", options: ["Klockan är två.", "Klockan är tolv.", "Vad är klockan?"], answer: "Klockan är två." },
  { module: "numbers", q: "Which is 20?", options: ["tjugo", "tio", "tolv"], answer: "tjugo" },

  { module: "food", q: "Translate: I would like coffee.", options: ["Jag skulle vilja ha kaffe.", "Jag heter kaffe.", "Vad kostar kaffe?"], answer: "Jag skulle vilja ha kaffe." },
  { module: "food", q: "Translate: How much does it cost?", options: ["Vad kostar det?", "Vad heter det?", "Varifrån kommer det?"], answer: "Vad kostar det?" },
  { module: "food", q: "Which means water?", options: ["vatten", "bröd", "mjölk"], answer: "vatten" },
  { module: "food", q: "Which means please / here you go?", options: ["Varsågod", "Ursäkta", "Hej"], answer: "Varsågod" },
  { module: "food", q: "Which means bread?", options: ["bröd", "mjölk", "kaffe"], answer: "bröd" },
  { module: "food", q: "Which is a polite order?", options: ["Jag skulle vilja ha kaffe.", "Ge kaffe nu.", "Jag heter kaffe."], answer: "Jag skulle vilja ha kaffe." },
  { module: "food", q: "Which means milk?", options: ["mjölk", "vatten", "språk"], answer: "mjölk" },
  { module: "food", q: "Which phrase includes thank you?", options: ["kaffe, tack", "kaffe, språk", "kaffe, klockan"], answer: "kaffe, tack" },
  { module: "food", q: "Which is an ett noun in this module?", options: ["ett vatten", "en kaffe", "en fråga"], answer: "ett vatten" },
  { module: "food", q: "What should you practice as a tiny dialogue?", options: ["Order, price, thanks", "Alphabet only", "Silent reading only"], answer: "Order, price, thanks" },

  { module: "workbook", q: "Best workbook habit?", options: ["Write, check, then speak aloud", "Only read the answer key", "Skip missed items"], answer: "Write, check, then speak aloud" },
  { module: "workbook", q: "After checking an answer, what should you do?", options: ["Say it aloud", "Delete it", "Skip the chapter"], answer: "Say it aloud" },
  { module: "workbook", q: "What should you learn with each noun?", options: ["Its article: en or ett", "Only its first letter", "Only its English translation"], answer: "Its article: en or ett" },
  { module: "workbook", q: "Best review timing?", options: ["Review missed items tomorrow", "Wait one month", "Never repeat"], answer: "Review missed items tomorrow" },
  { module: "workbook", q: "What is the best first speaking goal?", options: ["Clear and slow", "Fast and perfect", "Silent reading only"], answer: "Clear and slow" },
  { module: "workbook", q: "What should you do with missed answers?", options: ["Repeat them next day", "Ignore them", "Only mark wrong"], answer: "Repeat them next day" },
  { module: "workbook", q: "What should you read before workbook exercises?", options: ["The textbook model", "Only the last page", "Nothing"], answer: "The textbook model" },
  { module: "workbook", q: "Which is a good noun study pair?", options: ["en bok / ett språk", "bok / book only", "språk / language only"], answer: "en bok / ett språk" },
  { module: "workbook", q: "Which phrase means I practice Swedish every day?", options: ["Jag övar svenska varje dag.", "Jag kostar svenska.", "Jag heter varje dag."], answer: "Jag övar svenska varje dag." },
  { module: "workbook", q: "What is a good next-day review target?", options: ["Only missed answers first", "Only correct answers", "No review"], answer: "Only missed answers first" }
];
